name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/postgres-fe

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        postgres_version: [15, 16, 17]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        build-args: VERSION=${{ matrix.postgres_version }}
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.postgres_version }}
          ${{ matrix.postgres_version == 17 && format('{0}:latest', env.IMAGE_NAME) || '' }}
